#!/usr/bin/env python

import sys
import alignment

# Command-line arguments
if(len(sys.argv) != 3):
    print("Usage: ./needle FILE1 FILE2")
f1 = open(sys.argv[1], 'r')
seq1 = f1.read()
seq1 = seq1.split(" ")

f2 = open(sys.argv[2], 'r')
seq2 = f2.read()
seq2 = seq2.split(" ")

alignment.needle(seq1, seq2)
